name: nitamono 
description: "sizecheck aps"
publish_to: 'none'

version: 1.1.1+2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai:
  image_picker:
  flutter_dotenv:
  url_launcher:
  google_mobile_ads:
  webview_flutter:


  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"