name: nitamono 
description: "sizecheck aps"
publish_to: 'none'

version: 1.8.0+10

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai:
  image_picker:
  flutter_dotenv:
  url_launcher:
  google_mobile_ads:
  webview_flutter:


  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  shared_preferences: ^2.5.3
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/icon.png"
  image_path_android: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"